name: 'Tiny Tapeout Gate Level test'
description: 'This action will copy the GL netlist from the GDS action and run your testbench on it'
branding:
  color: purple
  icon: check
inputs:
  test-dir:
    description: 'The directory with the Makefile for running the tests'
    required: true
    default: 'test'

runs:
  using: 'composite'
  steps:
    - name: Download GDS artifact
      uses: actions/download-artifact@v4
      with:
        name: tt_submission

    - name: Set up environment variables
      shell: bash
      run: |
        cat << EOF >> $GITHUB_ENV
        PDK_ROOT=/home/runner/pdk
        PDK=sky130A
        IVERILOG_TAG=master
        IVERILOG_ROOT=/home/runner/iverilog
        EOF

    - name: Install Sky130 PDK
      uses: TinyTapeout/volare-action@v2
      with:
        pdk_name: sky130
        pdk_version: cd1748bb197f9b7af62a54507de6624e30363943
        pdk_root: /home/runner/pdk

    # Set Python up and install cocotb
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install cocotb (if required)
      if: ${{ hashFiles('test/requirements.txt') == '' }}
      shell: bash
      run: pip install cocotb==1.8.0

    - name: Install Python packages
      if: ${{ hashFiles('test/requirements.txt') != '' }}
      shell: bash
      run: pip install -r test/requirements.txt

    # - name: Install iverilog
    #   shell: bash
    #   run: sudo apt-get update && sudo apt-get install -y iverilog
    - name: Install the latest iverilog w/ SDF annotation interconnect support
      shell: bash
      run: | 
        cat << EOF >> $GITHUB_ENV
        IVERILOG_ROOT=/home/runner/iverilog
        IVERILOG_TAG=master
        EOF
        mkdir -p $IVERILOG_ROOT
        cd $IVERILOG_ROOT
        git clone --depth=1 --branch $IVERILOG_TAG https://github.com/steveicarus/iverilog.git .
        sudo apt-get install -y autoconf gperf make gcc g++ bison flex
        sh autoconf.sh
        ./configure --prefix=$IVERILOG_ROOT
        make 
        make install
        echo "$IVERILOG_ROOT/bin" >> $GITHUB_PATH


    - name: Install fixed TT Sim files
      shell: bash
      run: |
        cd test
        mkdir pdk_cleaned
        git clone --filter=blob:none --no-checkout https://github.com/efabless/caravel_mgmt_soc_litex.git pdk_cleaned
        cd pdk_cleaned
        git sparse-checkout set verilog/cvc-pdk
        git checkout

    - name: Run tests
      shell: bash
      run: |
        cp -rf tt_submission "${{ inputs.test-dir }}/gln"
        cp -rf sdf "${{ inputs.test-dir }}/sdf"
        cd "${{ inputs.test-dir }}"
        python3 rename_gl_final.py -gln_src=./gln/ -sdf_src=./sdf/ -sdf_dst=./sdf_renamed_out/ -gln_dst=./gln_renamed_out/
        rm -f tb.vcd results.xml
        make clean
        ls ./pdk_cleaned/verilog/cvc-pdk
        make GATES=yes SIM=icarus FIXED_PDK_DIR=./pdk_cleaned/verilog/cvc-pdk
        test -f results.xml
        ! grep failure results.xml

    - name: Upload VCD
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: gatelevel_test_vcd
          path: |
            ${{ inputs.test-dir }}/theta_sweep.png
            ${{ inputs.test-dir }}/tb.vcd
            ${{ inputs.test-dir }}/results.xml

    - name: Test Summary
      if: always()
      uses: test-summary/action@v2.3
      with:
        paths: ${{ inputs.test-dir }}/results.xml
